//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace UI.sct
{

    public partial class Auditoria : XPLiteObject
    {
        Guid fIdAuditoria;
        [Key(true)]
        public Guid IdAuditoria
        {
            get { return fIdAuditoria; }
            set { SetPropertyValue<Guid>(nameof(IdAuditoria), ref fIdAuditoria, value); }
        }
        string fNombreTabla;
        [Size(150)]
        public string NombreTabla
        {
            get { return fNombreTabla; }
            set { SetPropertyValue<string>(nameof(NombreTabla), ref fNombreTabla, value); }
        }
        string fIdentificador;
        [Size(500)]
        public string Identificador
        {
            get { return fIdentificador; }
            set { SetPropertyValue<string>(nameof(Identificador), ref fIdentificador, value); }
        }
        int fIdUsuario;
        public int IdUsuario
        {
            get { return fIdUsuario; }
            set { SetPropertyValue<int>(nameof(IdUsuario), ref fIdUsuario, value); }
        }
        DateTime fFecha;
        public DateTime Fecha
        {
            get { return fFecha; }
            set { SetPropertyValue<DateTime>(nameof(Fecha), ref fFecha, value); }
        }
        string fDireccionEquipo;
        [Size(25)]
        public string DireccionEquipo
        {
            get { return fDireccionEquipo; }
            set { SetPropertyValue<string>(nameof(DireccionEquipo), ref fDireccionEquipo, value); }
        }
    }

}
