//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace UI.sct
{

    public partial class ParametroSistema : XPLiteObject
    {
        string fIdParametroSistema;
        [Key]
        [Size(150)]
        public string IdParametroSistema
        {
            get { return fIdParametroSistema; }
            set { SetPropertyValue<string>(nameof(IdParametroSistema), ref fIdParametroSistema, value); }
        }
        string fDescripcion;
        [Size(250)]
        public string Descripcion
        {
            get { return fDescripcion; }
            set { SetPropertyValue<string>(nameof(Descripcion), ref fDescripcion, value); }
        }
        string fValor;
        [Size(500)]
        public string Valor
        {
            get { return fValor; }
            set { SetPropertyValue<string>(nameof(Valor), ref fValor, value); }
        }
        DateTime fFechaModificacion;
        public DateTime FechaModificacion
        {
            get { return fFechaModificacion; }
            set { SetPropertyValue<DateTime>(nameof(FechaModificacion), ref fFechaModificacion, value); }
        }
        int fIdUsuarioModificacion;
        public int IdUsuarioModificacion
        {
            get { return fIdUsuarioModificacion; }
            set { SetPropertyValue<int>(nameof(IdUsuarioModificacion), ref fIdUsuarioModificacion, value); }
        }
        string fDireccionEquipoModificacion;
        [Size(25)]
        public string DireccionEquipoModificacion
        {
            get { return fDireccionEquipoModificacion; }
            set { SetPropertyValue<string>(nameof(DireccionEquipoModificacion), ref fDireccionEquipoModificacion, value); }
        }
    }

}
