//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace UI.sct
{

    public partial class Usuario : XPLiteObject
    {
        int fIdUsuario;
        [Key(true)]
        public int IdUsuario
        {
            get { return fIdUsuario; }
            set { SetPropertyValue<int>(nameof(IdUsuario), ref fIdUsuario, value); }
        }
        Rol fIdRol;
        [Association(@"UsuarioReferencesRol")]
        public Rol IdRol
        {
            get { return fIdRol; }
            set { SetPropertyValue<Rol>(nameof(IdRol), ref fIdRol, value); }
        }
        string fNombres;
        public string Nombres
        {
            get { return fNombres; }
            set { SetPropertyValue<string>(nameof(Nombres), ref fNombres, value); }
        }
        string fApellidos;
        public string Apellidos
        {
            get { return fApellidos; }
            set { SetPropertyValue<string>(nameof(Apellidos), ref fApellidos, value); }
        }
        string fSexo;
        [Size(1)]
        public string Sexo
        {
            get { return fSexo; }
            set { SetPropertyValue<string>(nameof(Sexo), ref fSexo, value); }
        }
        string fDNI;
        [Size(16)]
        public string DNI
        {
            get { return fDNI; }
            set { SetPropertyValue<string>(nameof(DNI), ref fDNI, value); }
        }
        string fFechaNacimiento;
        [Size(20)]
        public string FechaNacimiento
        {
            get { return fFechaNacimiento; }
            set { SetPropertyValue<string>(nameof(FechaNacimiento), ref fFechaNacimiento, value); }
        }
        string fTelefono;
        [Size(20)]
        public string Telefono
        {
            get { return fTelefono; }
            set { SetPropertyValue<string>(nameof(Telefono), ref fTelefono, value); }
        }
        string fCorreo;
        public string Correo
        {
            get { return fCorreo; }
            set { SetPropertyValue<string>(nameof(Correo), ref fCorreo, value); }
        }
        string fDireccion;
        [Size(500)]
        public string Direccion
        {
            get { return fDireccion; }
            set { SetPropertyValue<string>(nameof(Direccion), ref fDireccion, value); }
        }
        string fCiudad;
        public string Ciudad
        {
            get { return fCiudad; }
            set { SetPropertyValue<string>(nameof(Ciudad), ref fCiudad, value); }
        }
        string fPais;
        public string Pais
        {
            get { return fPais; }
            set { SetPropertyValue<string>(nameof(Pais), ref fPais, value); }
        }
        string fUsuario1;
        [Size(40)]
        [Persistent(@"Usuario")]
        public string Usuario1
        {
            get { return fUsuario1; }
            set { SetPropertyValue<string>(nameof(Usuario1), ref fUsuario1, value); }
        }
        string fContrasena;
        public string Contrasena
        {
            get { return fContrasena; }
            set { SetPropertyValue<string>(nameof(Contrasena), ref fContrasena, value); }
        }
        int fActivo;
        public int Activo
        {
            get { return fActivo; }
            set { SetPropertyValue<int>(nameof(Activo), ref fActivo, value); }
        }
        DateTime fFechaUltimaConexion;
        public DateTime FechaUltimaConexion
        {
            get { return fFechaUltimaConexion; }
            set { SetPropertyValue<DateTime>(nameof(FechaUltimaConexion), ref fFechaUltimaConexion, value); }
        }
        DateTime fFechaUltimoCambioContrasena;
        public DateTime FechaUltimoCambioContrasena
        {
            get { return fFechaUltimoCambioContrasena; }
            set { SetPropertyValue<DateTime>(nameof(FechaUltimoCambioContrasena), ref fFechaUltimoCambioContrasena, value); }
        }
        bool fIdEstadoRegistro;
        public bool IdEstadoRegistro
        {
            get { return fIdEstadoRegistro; }
            set { SetPropertyValue<bool>(nameof(IdEstadoRegistro), ref fIdEstadoRegistro, value); }
        }
        DateTime fFechaCreacion;
        public DateTime FechaCreacion
        {
            get { return fFechaCreacion; }
            set { SetPropertyValue<DateTime>(nameof(FechaCreacion), ref fFechaCreacion, value); }
        }
        int fIdUsuarioCreacion;
        public int IdUsuarioCreacion
        {
            get { return fIdUsuarioCreacion; }
            set { SetPropertyValue<int>(nameof(IdUsuarioCreacion), ref fIdUsuarioCreacion, value); }
        }
        string fDireccionEquipoCreacion;
        [Size(25)]
        public string DireccionEquipoCreacion
        {
            get { return fDireccionEquipoCreacion; }
            set { SetPropertyValue<string>(nameof(DireccionEquipoCreacion), ref fDireccionEquipoCreacion, value); }
        }
        DateTime fFechaModificacion;
        public DateTime FechaModificacion
        {
            get { return fFechaModificacion; }
            set { SetPropertyValue<DateTime>(nameof(FechaModificacion), ref fFechaModificacion, value); }
        }
        int fIdUsuarioModificacion;
        public int IdUsuarioModificacion
        {
            get { return fIdUsuarioModificacion; }
            set { SetPropertyValue<int>(nameof(IdUsuarioModificacion), ref fIdUsuarioModificacion, value); }
        }
        string fDireccionEquipoModificacion;
        [Size(25)]
        public string DireccionEquipoModificacion
        {
            get { return fDireccionEquipoModificacion; }
            set { SetPropertyValue<string>(nameof(DireccionEquipoModificacion), ref fDireccionEquipoModificacion, value); }
        }
        [Association(@"ReparacionReferencesUsuario")]
        public XPCollection<Reparacion> Reparacions { get { return GetCollection<Reparacion>(nameof(Reparacions)); } }
        [Association(@"ReparacionReferencesUsuario1")]
        public XPCollection<Reparacion> Reparacions1 { get { return GetCollection<Reparacion>(nameof(Reparacions1)); } }
    }

}
