//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace SCT.sct
{

    public partial class AuditoriaDetalle : XPLiteObject
    {
        string fValorNuevo;
        [Size(SizeAttribute.Unlimited)]
        public string ValorNuevo
        {
            get { return fValorNuevo; }
            set { SetPropertyValue<string>(nameof(ValorNuevo), ref fValorNuevo, value); }
        }
        string fValorAnterior;
        [Size(SizeAttribute.Unlimited)]
        public string ValorAnterior
        {
            get { return fValorAnterior; }
            set { SetPropertyValue<string>(nameof(ValorAnterior), ref fValorAnterior, value); }
        }
        public struct CompoundKey1Struct
        {
            [Persistent("IdAuditoria")]
            public Guid IdAuditoria { get; set; }
            [Persistent("NombreColumna")]
            public string NombreColumna { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
