//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace SCT.sct
{

    public partial class DetalleReparacion : XPLiteObject
    {
        int fIdDetalleReparacion;
        [Key(true)]
        public int IdDetalleReparacion
        {
            get { return fIdDetalleReparacion; }
            set { SetPropertyValue<int>(nameof(IdDetalleReparacion), ref fIdDetalleReparacion, value); }
        }
        Reparacion fIdReparacion;
        [Association(@"DetalleReparacionReferencesReparacion")]
        public Reparacion IdReparacion
        {
            get { return fIdReparacion; }
            set { SetPropertyValue<Reparacion>(nameof(IdReparacion), ref fIdReparacion, value); }
        }
        Equipo fIdEquipo;
        [Association(@"DetalleReparacionReferencesEquipo")]
        public Equipo IdEquipo
        {
            get { return fIdEquipo; }
            set { SetPropertyValue<Equipo>(nameof(IdEquipo), ref fIdEquipo, value); }
        }
        string fProblemaReportado;
        [Size(500)]
        public string ProblemaReportado
        {
            get { return fProblemaReportado; }
            set { SetPropertyValue<string>(nameof(ProblemaReportado), ref fProblemaReportado, value); }
        }
        string fObservacion;
        [Size(300)]
        public string Observacion
        {
            get { return fObservacion; }
            set { SetPropertyValue<string>(nameof(Observacion), ref fObservacion, value); }
        }
    }

}
