//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace SCT.sct
{

    public partial class Equipo : XPLiteObject
    {
        int fIdEquipo;
        [Key(true)]
        public int IdEquipo
        {
            get { return fIdEquipo; }
            set { SetPropertyValue<int>(nameof(IdEquipo), ref fIdEquipo, value); }
        }
        Categoria fIdCategoria;
        [Association(@"EquipoReferencesCategoria")]
        public Categoria IdCategoria
        {
            get { return fIdCategoria; }
            set { SetPropertyValue<Categoria>(nameof(IdCategoria), ref fIdCategoria, value); }
        }
        string fMarca;
        public string Marca
        {
            get { return fMarca; }
            set { SetPropertyValue<string>(nameof(Marca), ref fMarca, value); }
        }
        string fModelo;
        public string Modelo
        {
            get { return fModelo; }
            set { SetPropertyValue<string>(nameof(Modelo), ref fModelo, value); }
        }
        string fSerie;
        public string Serie
        {
            get { return fSerie; }
            set { SetPropertyValue<string>(nameof(Serie), ref fSerie, value); }
        }
        string fColor;
        public string Color
        {
            get { return fColor; }
            set { SetPropertyValue<string>(nameof(Color), ref fColor, value); }
        }
        string fDescripcion;
        [Size(500)]
        public string Descripcion
        {
            get { return fDescripcion; }
            set { SetPropertyValue<string>(nameof(Descripcion), ref fDescripcion, value); }
        }
        bool fIdEstadoRegistro;
        public bool IdEstadoRegistro
        {
            get { return fIdEstadoRegistro; }
            set { SetPropertyValue<bool>(nameof(IdEstadoRegistro), ref fIdEstadoRegistro, value); }
        }
        DateTime fFechaCreacion;
        public DateTime FechaCreacion
        {
            get { return fFechaCreacion; }
            set { SetPropertyValue<DateTime>(nameof(FechaCreacion), ref fFechaCreacion, value); }
        }
        int fIdUsuarioCreacion;
        public int IdUsuarioCreacion
        {
            get { return fIdUsuarioCreacion; }
            set { SetPropertyValue<int>(nameof(IdUsuarioCreacion), ref fIdUsuarioCreacion, value); }
        }
        string fDireccionEquipoCreacion;
        [Size(25)]
        public string DireccionEquipoCreacion
        {
            get { return fDireccionEquipoCreacion; }
            set { SetPropertyValue<string>(nameof(DireccionEquipoCreacion), ref fDireccionEquipoCreacion, value); }
        }
        DateTime fFechaModificacion;
        public DateTime FechaModificacion
        {
            get { return fFechaModificacion; }
            set { SetPropertyValue<DateTime>(nameof(FechaModificacion), ref fFechaModificacion, value); }
        }
        int fIdUsuarioModificacion;
        public int IdUsuarioModificacion
        {
            get { return fIdUsuarioModificacion; }
            set { SetPropertyValue<int>(nameof(IdUsuarioModificacion), ref fIdUsuarioModificacion, value); }
        }
        string fDireccionEquipoModificacion;
        [Size(25)]
        public string DireccionEquipoModificacion
        {
            get { return fDireccionEquipoModificacion; }
            set { SetPropertyValue<string>(nameof(DireccionEquipoModificacion), ref fDireccionEquipoModificacion, value); }
        }
        [Association(@"DetalleReparacionReferencesEquipo")]
        public XPCollection<DetalleReparacion> DetalleReparacions { get { return GetCollection<DetalleReparacion>(nameof(DetalleReparacions)); } }
    }

}
