//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace SCT.sct
{

    public partial class HistorialDireccionEquipo : XPLiteObject
    {
        int fCantidadPeticion;
        [ColumnDbDefaultValue("((0))")]
        public int CantidadPeticion
        {
            get { return fCantidadPeticion; }
            set { SetPropertyValue<int>(nameof(CantidadPeticion), ref fCantidadPeticion, value); }
        }
        DateTime fFechaUltimaEjecucion;
        public DateTime FechaUltimaEjecucion
        {
            get { return fFechaUltimaEjecucion; }
            set { SetPropertyValue<DateTime>(nameof(FechaUltimaEjecucion), ref fFechaUltimaEjecucion, value); }
        }
        public struct CompoundKey1Struct
        {
            [Persistent("Fecha")]
            public DateTime Fecha { get; set; }
            [Size(25)]
            [Persistent("DireccionEquipo")]
            public string DireccionEquipo { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
